#
# Alpine base image, see README for more details
#
# VERSION               1.0.1
#
FROM alpine:3.8

#
# Standard environment variables
#
ENV TZ="GMT+08" LANG="C.UTF-8"

#
# Standard pre-installed libraries
#
RUN apk add --no-cache bash curl wget vim iputils gettext grep

#
# Standard folders, and WORKDIR
#
RUN mkdir -p /entrypoint/ /application/ /storage/
WORKDIR /appspace/

#
# Standard entrypoint script setup
# Script contents : https://github.com/uilicious/uilicious-dockerfile/blob/master/base/alpine-base/entrypoint-base.sh
#
COPY entrypoint-base.sh /entrypoint/base.sh
RUN chmod 555 /entrypoint/base.sh
ENTRYPOINT ["/entrypoint/base.sh"]