##########################################################################
#
#  Simple nginx server that returns a blank hello
#
##########################################################################
FROM nginx:alpine


RUN ls -alh /usr/share/nginx/html;
RUN cat /usr/share/nginx/html/index.html

#RUN ls -alh /etc/nginx/conf.d
#RUN cat /etc/nginx/nginx.conf
#RUN cat /etc/nginx/conf.d/default.conf

EXPOSE 80

