##########################################################################
#
#  Node image, with cli pre installed + git (via buster)
#
##########################################################################
FROM node:16-buster

RUN npm install -g netlify-cli@8.19.3
